# Generated by Django 3.2.6 on 2021-08-18 13:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('bio', models.TextField()),
                ('skills', models.TextField()),
                ('school', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('Degree', models.CharField(max_length=100)),
                ('work_title', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=250)),
                ('start_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=30)),
                ('interest', models.TextField()),
                ('refrence_id', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
