# Generated by Django 3.2.6 on 2021-08-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume_details',
            old_name='refrence_id',
            new_name='reference_id',
        ),
    ]
