# Generated by Django 3.2.6 on 2021-08-19 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210818_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('date_recieved', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
