# Generated by Django 3.2.6 on 2021-08-19 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_recieved',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
